### ISSUE TITLE
无法获取gitmojis.json文件问题——解决方案提议

### ISSUE THREAD

**Issue by HaiRongHaHA** [arvinxx/gitmoji-commit-workflow#128]
您好，ccommitlint-plugin-gitmoji使用时 Failed to fetch gitmoji JSON，看了您的文档解决方法需要自己下载gitmojis.json文件放node_modules里，我觉得这样不太合理，这样我和我的搭档一起写代码我们都需要下载一份这个文件放本地node_modules。我觉得这个文件您可以下载放在您的包里，如果Failed to fetch gitmoji JSON就引用您项目内的gitmojis.json文件，这样使用起来更友好些，您觉得呢？

**Comment by wowohuai** [comment]
可以在根目录下放 .gitmoji.json文件
