### ISSUE TITLE
Stick to english

### ISSUE THREAD

**Issue by iuscare** [arvinxx/gitmoji-commit-workflow#17]
Hey there, could we stick to english or be able to modify the title types of the changelog?

**Comment by arvinxx** [comment]
yeah,that's ok. I will add this feature tomorrow -> By default stick to english and also you can switch your language in configuration.

**Comment by iuscare** [comment]
Thanks! Played a little bit with your configuration after I saw the appealing commits in your repos. Well done!

**Comment by arvinxx** [comment]
yeah, it's really a pleasure way to wirte commit in gitmoji ways with Angular commit style, which I call it Gitmoji Commit Message style 😄 I will also write an article to introduce it.

**Comment by iuscare** [comment]
Already read your motives in your article written in your native language after google translated it 😄 

Btw.: I dunno if it is already possible by using `writerOpts` within the `@semantic-release/release-notes-generator` config, but it would also be helpful, to be able to add or delete additional CommitTypes, which should be written into the changelog (e.g. one could prefer to add doc type commits or delete refactoring type commits).

**Comment by arvinxx** [comment]
yeah. Actually I have done a little configuartion for changelog.(I'm not writting doc by now).

For example. You can see that the [.changelogrc.js](https://github.com/arvinxx/gitmoji-commit-workflow/blob/master/.changelogrc.js) file , that there is a param of `displayTypes` to show the types you want to display.
beside, i have made an another param 'scopeDisplayName' to map the scope in commit to changelog name.
It work will on this repo and  my other project like [power-yuque](https://github.com/arvinxx/power-yuque/blob/master/CHANGELOG.md) .

As for next step, I have a plan to add more config like just ignore some type to display, trigger whether using emoji in changelog, customize the title for each type and so on.
If you have any demand, welcome to post issues~😄

**Comment by arvinxx** [comment]
@iuscare  hi, `conventional-changelog-gitmoji-config@1.4.0` is released. please check the [configuration](https://github.com/arvinxx/gitmoji-commit-workflow/tree/master/packages/changelog#configuration-file)

**Comment by iuscare** [comment]
You literally rock! Not only do you provide an appealing repo look, but also a workflow for organizing and keeping a much cleaner repo! Thank you so much :-)
