### ISSUE TITLE
Question: Add this to commitlint community-projects?

### ISSUE THREAD

**Issue by escapedcat** [arvinxx/gitmoji-commit-workflow#396]
Heyhey, would you mind we add your config here?:  https://commitlint.js.org/#/reference-community-projects

See:  
https://github.com/conventional-changelog/commitlint/issues/3036#issuecomment-1045963649

**Comment by arvinxx** [comment]
Yes ~ I'm pleasure to be added.

**Comment by escapedcat** [comment]
Cool,  done: https://commitlint.js.org/#/reference-community-projects
