### ISSUE TITLE
Customize gitmojis URL

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [arvinxx/gitmoji-commit-workflow#40]
I see it is hardcoded here: https://github.com/arvinxx/gitmoji-commit-workflow/blob/7f762dad916f65b15e825af4fd59b14237e19c98/packages/plugin/src/gitmojiCode.ts#L9

Could it also possibly link to a local file?

**Comment by arvinxx** [comment]
@aureooms  It's possible i think. Let me think about it.

**Comment by make-github-pseudonymous-again** [comment]
Thanks!
