### ISSUE TITLE
`commitlint` dependency is redundant for `plugin-gitmoji`

### ISSUE THREAD

**Issue by PAXANDDOS** [arvinxx/gitmoji-commit-workflow#470]
Hey! I'm new to the whole 'commitlint' thing and was messing around and found possibly redundant dependency.

`commitlint@"^11.0.0` required by `commitlint-plugin-gitmoji` and' is required by `commitlint-config-gitmoji` seems to be redundant. Furthermore, even with installed `commitlint`, it would show an error that says I got the wrong version (required 11, latest 17).

So I got `commitlint` totally removed and ignored the warning message. And it works as expected! I got installed only `@commitlint/cli` (which seems to be the only package needed to get commitlint to work, according to official documentation), `commitlint-config-gitmoji`, and `@commitlint/types` (for config file).

Don't you find this dependency redundant? Or at least outdated

**Comment by tianyingchun** [comment]
yes, should remove this peerDependencies.

**Comment by arvinxx** [comment]
fixed in  https://github.com/arvinxx/gitmoji-commit-workflow/releases/tag/commitlint-plugin-gitmoji%402.2.1
