### ISSUE TITLE
Commitlint plugin does not recognize ⬆️

### ISSUE THREAD

**Issue by jpolo** [arvinxx/gitmoji-commit-workflow#492]
The bug concerns the commitlint plugin/config.

I usea  custom config available [ in this repository](https://github.com/w5s/project-config/tree/main/packages/commitlint-config/src). It is possible to reproduce the bug by changing the value of anyGitmoji to '⬆️'.

The validation message is "Your commit should start with gitmoji code,please check the emoji code on https://gitmoji.dev/."

**Comment by jpolo** [comment]
Could reproduce with 🩹, so it seems to be a wider problem...

**Comment by jpolo** [comment]
It seems that using [is-fullwidth-code-point](https://www.npmjs.com/package/is-fullwidth-code-point)
And replacing the unicodeRegex with `unicodeResult = raw.split('').filter(isFullwidthCodePoint);` would validate the commit message.
Would you accept a PR, or is this repo dead ?

**Comment by srizzon** [comment]
I have the same problem with 🧪 and 🏗️.

I found this [regex ](https://github.com/arvinxx/gitmoji-commit-workflow/blob/c986d43c8e4a20a947a66a44881528655e1fa218/packages/commitlint-plugin/src/rule.ts) (line 10) and I made a list of all emojis based on this [json](https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json) and a lot of emojis doesn't match with this regex.

Sample: https://regex101.com/r/BS5M9a/1

This regex work as well: https://regex101.com/r/R7drml/1 but I'm not sure about this solution.

**Comment by mehdicopter** [comment]
I found this as well, and I think this project is dead :/

**Comment by arvinxx** [comment]
fixed in `commitlint-plugin-gitmoji@2.2.5`
