### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by orefalo** [arvinxx/gitmoji-commit-workflow#658]
Getting this error, any idea?

<img width="440" alt="image" src="https://user-images.githubusercontent.com/52085/209851157-97c07c57-dc6f-4cfb-9a5f-30629bdeaa92.png">

Can we relax the dependency to commintilnt 11 ?

**Comment by arvinxx** [comment]
maybe you can try with the latest version of commitlint-config-gitmoji ?

**Comment by orefalo** [comment]
didn't work.
but switched to commit zen, removed your pkg and it's a neat alternative.
