### ISSUE TITLE
Commitlint Plugin yields false positive for some Unicode characters

### ISSUE THREAD

**Issue by switchnollie** [arvinxx/gitmoji-commit-workflow#662]
Hello @arvinxx, 

First of all amazing project. I'm using your commitlint config for a Gitlab project. On Gitlab, I can't use the codes for Gitmoji, but I use the regular Unicode Emojis (this is the standard setting for the VS Code plugin that I use anyway).

The RegEx that you used in https://github.com/arvinxx/gitmoji-commit-workflow/blob/master/packages/commitlint-plugin/src/rule.ts#L11 does not work for every Gitmoji and I get this commitlint error for a correctly formatted commit message:

```
Your commit should start with gitmoji code,please check the emoji code on https://gitmoji.dev/. [start-with-gitmoji]
```

The emoji I faced the issue was 🩹 and ✏️, I could verify it's not working with the Regex101 link (try out `🩹 chore(scope): test`).

Thank you for your support!

**Comment by arvinxx** [comment]
It seems related with #56?

**Comment by switchnollie** [comment]
This Regex101 Link evaluates your regex with all possible Gitmoji Unicodes. Only 28 of the 73 Gitmojis work with your Plugin. This makes it currently not usable.

https://regex101.com/r/shBTBg/1

**Comment by arvinxx** [comment]
> This Regex101 Link evaluates your regex with all possible Gitmoji Unicodes. Only 28 of the 73 Gitmojis work with your Plugin. This makes it currently not usable.
> 
> https://regex101.com/r/shBTBg/1

I will try to fix it this month.

**Comment by switchnollie** [comment]
Thank you for the fix, works perfectly now!
