### ISSUE TITLE
Help wanted. gitmoji is not running as expected

### ISSUE THREAD

**Issue by hugovidafe** [arvinxx/gitmoji-commit-workflow#664]
Package: [commitlint-config-gitmoji](https://github.com/arvinxx/gitmoji-commit-workflow/blob/master/packages/commitlint-config)

![image](https://user-images.githubusercontent.com/69076992/213655533-9288710b-cc64-4e23-801c-ef51ab9a84a6.png)

**Comment by arvinxx** [comment]
Your commit is not fit for the v2 rule. You can try with v1.

**Comment by hugovidafe** [comment]
v1 of what package?
Talking about commitling or [commitlint-config-gitmoji](https://github.com/arvinxx/gitmoji-commit-workflow/blob/master/packages/commitlint-config)
